import { UserProvider } from '@auth0/nextjs-auth0/client';
import type { Metadata } from 'next';
import '../styles/styles.css';
// import './globals.css';

import AuthWrapper from '@/components/AuthWrapper/AuthWrapper';
import { ReactNode } from 'react';

// const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <head>
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <link
          rel="shortcut icon mask-icon"
          href="https://cdn.auth0.com/website/auth0_favicon.svg"
          color="#000000"
        />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
      </head>
      <body
      // className={ inter.className }
      >
        <UserProvider>
          <AuthWrapper>
            <>{children}</>
          </AuthWrapper>
        </UserProvider>
      </body>
    </html>
  );
}
