

import { UserProvider,  } from '@auth0/nextjs-auth0/client'
import './globals.css'
import  '../styles/styles.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import AuthWrapper from '@/components/AuthWrapper/AuthWrapper'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {  
  
  return (
    <html lang="en">
      <head>
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <link
          rel="shortcut icon mask-icon"
          href="https://cdn.auth0.com/website/auth0_favicon.svg"
          color="#000000"
        />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
      </head>
      <body>
        <UserProvider
        // loginUrl='/api/auth/login' profileUrl='/profile'
        >
          <AuthWrapper>
            <>
              { children }
            </>
          </AuthWrapper>
        </UserProvider>
      </body>
    </html>
     
   
  );
}
